grails-app/controllers/mz/org/fgh/sifmoz/backend/group/GroupInfoController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/group/GroupPackHeaderController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/group/groupMemberPrescriptionController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/prescription/PrescriptionController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/group/GroupPack.groovy
=> alteracoes modulo de grupos

grails-app/controllers/mz/org/fgh/sifmoz/backend/episode/EpisodeController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/patient/PatientController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/patientIdentifier/PatientServiceIdentifier.groovy, grails-app/init/sifmoz/backend/BootStrap.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/packaging/RestPackService.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/restUtils/RestOpenMRSClient.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/utilities/JSONSerializer.groovy
- Add funcionality for Referral Pharmacies
- Optmize Load patient from OpenMRS
=> idmed-backendchanges

grails-app/controllers/mz/org/fgh/sifmoz/backend/patientVisit/PatientVisitController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/service/ClinicalService.groovy
- Ajuste na Atencao FArmaceutica
=> Update backend after Integration

grails-app/controllers/mz/org/fgh/sifmoz/backend/patient/PatientController.groovy
fix pesquisa nid modulo de grupos
=> fix pesquisa nid modulo de grupos

grails-app/controllers/mz/org/fgh/sifmoz/backend/clinicSector/ClinicSectorController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/clinicSector/ClinicSector.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/clinicSector/RestClinicSectorService.groovy
- Post ClinicSector Data to Central DB for iDART Mobile Sync DC
=> BackEnd Updated Sync ClinicSector

grails-app/controllers/mz/org/fgh/sifmoz/backend/patient/PatientController.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/clinicSector/RestClinicSectorService.groovy
=> Pesquisa do Paciente

grails-app/services/mz/org/fgh/sifmoz/backend/tansreference/RestPostPatientCentralMobileService.groovy
- Ultima prescricao dispensada antes da Referencia
=> Envio de Dados do Paciente

grails-app/conf/application.yml, grails-app/domain/mz/org/fgh/sifmoz/backend/patientVisit/PatientVisit.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/screening/AdherenceScreening.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/screening/PregnancyScreening.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/screening/RAMScreening.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/screening/TBScreening.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/screening/VitalSignsScreening.groovy
=> Padronizacao de Domain Class

grails-app/controllers/mz/org/fgh/sifmoz/backend/patient/PatientController.groovy
=> bug fix patientnot updating

grails-app/domain/mz/org/fgh/sifmoz/backend/clinicSector/ClinicSector.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/packagedDrug/PackagedDrug.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/packaging/Pack.groovy, grails-app/init/sifmoz/backend/BootStrap.groovy
- Remove defaultValue on Mapping Update BootStrap
- Add new uuid for TDF+Prep regimen
=> Update Domain Class

grails-app/controllers/mz/org/fgh/sifmoz/backend/healthInformationSystem/HealthInformationSystemController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/healthInformationSystem/HealthInformationSystem.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/protection/SecUser.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/packaging/RestPackService.groovy
=> Update Sync Pack to OpenMRs

grails-app/domain/mz/org/fgh/sifmoz/backend/prescriptionDetail/PrescriptionDetail.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/restUtils/RestOpenMRSClient.groovy
=> Change Pack Formulation

grails-app/controllers/mz/org/fgh/sifmoz/backend/openmrsErrorLog/OpenmrsErrorLogController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/patientVisitDetails/PatientVisitDetailsController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/openmrsErrorLog/OpenmrsErrorLog.groovy, grails-app/init/sifmoz/backend/BootStrap.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/openmrsErrorLog/OpenmrsErrorLogService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/packaging/RestPackService.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/restUtils/RestOpenMRSClient.groovy, src/integration-test/groovy/mz/org/fgh/sifmoz/backend/OpenmrsErrorLogServiceSpec.groovy, src/integration-test/groovy/mz/org/fgh/sifmoz/backend/openmrsErrorLog/OpenmrsErrorLogServiceSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/OpenmrsErrorLogControllerSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/OpenmrsErrorLogSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/openmrsErrorLog/OpenmrsErrorLogControllerSpec.groovy
Criacao da gestao de registo de Erro na Sincronizacao com OpenMRS
=> Jira Ticket #Pharm 100

grails-app/controllers/mz/org/fgh/sifmoz/backend/healthInformationSystem/SystemConfigsController.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/episode/EpisodeService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/packaging/PackService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/prescription/IPrescriptionService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/prescription/PrescriptionService.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/migration/entity/pack/PackageMigrationRecord.groovy
fix relatorios referencia , fix migracao clinicSector , fix initailization
=> fix relatorios referencia , fix migracao clinicSector , fix initailization

grails-app/services/mz/org/fgh/sifmoz/backend/tansreference/RestGetDispensesCentralMobileService.groovy
Add SyncStatus and Provider to DC or DD dispensation
=> OpenMRs Sync

grails-app/init/sifmoz/backend/BootStrap.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/tansreference/RestGetDispensesCentralMobileService.groovy
- Sync dispense with correct dispenseMode
=> Update Sync DD/DC

grails-app/controllers/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReportController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReport.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/prescription/PrescriptionService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/INotSynchronizingPacksOpenMrsReportService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReportService.groovy, src/integration-test/groovy/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/INotSynchronizingPacksOpenMrsReportServiceSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReportControllerSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReportServiceSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/reports/monitoringAndEvaluation/NotSynchronizingPacksOpenMrsReportSpec.groovy
relatorio de erros de interobilidade
=> relatorio de erros de interobilidade

grails-app/controllers/mz/org/fgh/sifmoz/backend/episode/EpisodeController.groovy, grails-app/controllers/mz/org/fgh/sifmoz/backend/tansreference/PatientTransReferenceController.groovy, grails-app/controllers/sifmoz/backend/UrlMappings.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/tansreference/PatientTransReference.groovy, grails-app/init/sifmoz/backend/BootStrap.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/tansreference/RestPostPatientCentralMobileService.groovy, grails-app/utils/mz/org/fgh/sifmoz/backend/convertDateUtils/ConvertDateUtils.java
- Add routine to remove patients with more than 5 days synced info
=> Add Task for Sync Lost to followup patients for DC

grails-app/conf/application.yml, grails-app/init/sifmoz/backend/BootStrap.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/migration/fromDataSource/DataSourceMigrationService.groovy, grails-app/services/mz/org/fgh/sifmoz/backend/patientVisitDetails/PatientVisitDetailsDataSourceMigrationService.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/migration/fromDataSource/DataSourceMigrationServiceSpec.groovy, src/test/groovy/mz/org/fgh/sifmoz/backend/patientVisitDetails/PatientVisitDetailsDataSourceMigrationServiceSpec.groovy
- Migracao de dados para nova Base Migrada
=> Carregamento de Dados de uma Base de dados IDMED para outra

grails-app/controllers/mz/org/fgh/sifmoz/backend/tansreference/PatientTransReferenceController.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/patient/Patient.groovy, grails-app/domain/mz/org/fgh/sifmoz/backend/tansreference/PatientTransReference.groovy, grails-app/init/sifmoz/backend/BootStrap.groovy
fix role bug
alter table patient add column match_id integer;
WITH sequential_numbers AS (
SELECT id, 
ROW_NUMBER() OVER (ORDER BY id) AS seq_num
FROM patient
WHERE match_id IS NULL
)
UPDATE patient
SET match_id = seq_num
FROM sequential_numbers
WHERE patient.id = sequential_numbers.id
AND patient.match_id IS NULL;
alter table patient alter column match_id set not null;
ALTER TABLE patient
ADD constraint match_id_unique UNIQUE (match_id);
=> adding column match_id in patient

grails-app/domain/mz/org/fgh/sifmoz/backend/stockentrance/StockEntrance.groovy
No Ecra do Gruia de Entrada adicionar uma nota de Entrada do Guia.
=> iDMEDPHARM-114
